Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,49 +1,35 @@
-# Hourly scraping
-name: covidtrends
-
-# Controls when the action will run.
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: main
+    paths: ['**.Rmd']
 
+name: render-rmarkdown
 
-jobs: 
-  autocovid:
-    # The type of runner that the job will run on
-    runs-on: macOS-11
-
-    # Load repo and install R
+jobs:
+  render-rmarkdown:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-    - uses: actions/checkout@master
-    - uses: r-lib/actions/setup-r@master
+      - name: Checkout repo
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    # Set-up R
-    - name: Install packages
-      run: |
-        R -e 'install.packages("gtrendsR")'
-        R -e 'install.packages("magrittr")'
-        R -e 'install.packages("dplyr")'
-        R -e 'install.packages("xts")'
-        R -e 'install.packages("tbl2xts")'
-        R -e 'install.packages("dygraphs")'
-        R -e 'install.packages("rgdal")'
-        R -e 'install.packages("RColorBrewer")'
-        R -e 'install.packages("leaflet")'
-        R -e 'install.packages("wordcloud")'
-        R -e 'install.packages("flexdashboard")'
+      - uses: r-lib/actions/setup-pandoc@v1
+
+      - uses: r-lib/actions/setup-r@v1
+
+      - uses: r-lib/actions/setup-renv@v1
       
-    # Run R script
-    - name: Covid_Trends
-      run: Rscript covid_trends.Rmd
-      
- # Add new files in data folder, commit along with other modified files, push
-    - name: Commit files
-      run: |
-        git config --local user.name actions-user
-        git config --local user.email "actions@github.com"
-        git add data/*
-        git commit -am "GH ACTION Headlines $(date)"
-        git push origin main
-      env:
-        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
-        username: github-actions
+      - name: Render Rmarkdown files
+        run: |
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+      - name: Commit results
+        run: |
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
